apiVersion: v1
data:
  mapRoles: "- groups:\n  - system:masters\n  rolearn: arn:aws:iam::811850476365:role/UdacityFlaskDeployCBKubectlRole2\n
    \ username: build\n- groups:\n  - system:bootstrappers\n  - system:nodes\n  rolearn:
    arn:aws:iam::811850476365:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-OT95OK5QFQM\n
    \ username: system:node:{{EC2PrivateDNSName}}\n  \n"
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-03-06T03:21:54Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapUsers: {}
    manager: eksctl
    operation: Update
    time: "2021-03-06T03:21:54Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        f:mapRoles: {}
    manager: kubectl-patch
    operation: Update
    time: "2021-03-06T03:30:06Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2844"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 5a57df3c-3d32-4319-8d6c-f1ac78f81c58
